import { test } from "node:test";
import assert from "node:assert/strict";
import { buildCreateTable } from "./ddl.js";

const id = { name: "id", type: "bigint", primaryKey: true, identity: true };

test("builds a table with identity PK, defaults, not null and unique", () => {
  const { sql, error } = buildCreateTable({
    name: "customers",
    columns: [
      id,
      { name: "email", type: "text", nullable: false, unique: true },
      { name: "active", type: "boolean", default: { kind: "value", value: "true" } },
      { name: "created_at", type: "timestamptz", nullable: false, default: { kind: "now" } },
      { name: "note", type: "varchar", length: 200, default: { kind: "value", value: "it's new" } },
    ],
  });
  assert.equal(error, undefined);
  assert.equal(
    sql,
    [
      `CREATE TABLE "customers" (`,
      `  "id" bigint GENERATED BY DEFAULT AS IDENTITY,`,
      `  "email" text NOT NULL UNIQUE,`,
      `  "active" boolean DEFAULT true,`,
      `  "created_at" timestamptz DEFAULT now() NOT NULL,`,
      `  "note" varchar(200) DEFAULT 'it''s new'::varchar(200),`,
      `  CONSTRAINT "customers_pkey" PRIMARY KEY ("id")`,
      `);`,
    ].join("\n"),
  );
});

test("schema-qualifies non-public schemas and adds foreign keys", () => {
  const { sql } = buildCreateTable({
    schema: "shop",
    name: "orders",
    columns: [id, { name: "customer_id", type: "bigint", nullable: false }],
    foreignKeys: [{ column: "customer_id", refSchema: "shop", refTable: "customers", refColumn: "id", onDelete: "cascade" }],
  });
  assert.match(sql, /^CREATE TABLE "shop"\."orders" \(/);
  assert.match(sql, /CONSTRAINT "orders_customer_id_fkey" FOREIGN KEY \("customer_id"\) REFERENCES "shop"\."customers" \("id"\) ON DELETE CASCADE/);
});

test("composite primary key", () => {
  const { sql } = buildCreateTable({
    name: "memberships",
    columns: [
      { name: "user_id", type: "uuid", primaryKey: true },
      { name: "team_id", type: "uuid", primaryKey: true },
    ],
  });
  assert.match(sql, /PRIMARY KEY \("user_id", "team_id"\)/);
});

test("rejects unsafe or invalid input", () => {
  const cases = [
    [{ name: 'x"; DROP TABLE y; --', columns: [id] }, /can only use letters/],
    [{ name: "t", columns: [] }, /at least one column/],
    [{ name: "t", columns: [id, { ...id }] }, /Two columns/],
    [{ name: "t", columns: [{ name: "a", type: "text; DROP" }] }, /unsupported type/],
    [{ name: "t", columns: [{ name: "a", type: "integer", default: { kind: "value", value: "1; DROP" } }] }, /whole number/],
    [{ name: "t", columns: [{ name: "a", type: "text", identity: true }] }, /auto-increment only fits/],
    [{ name: "t", columns: [{ name: "a", type: "text", default: { kind: "now" } }] }, /only fits a date/],
    [{ name: "t", columns: [{ name: "a", type: "jsonb", default: { kind: "value", value: "{bad" } }] }, /valid JSON/],
    [{ name: "t", columns: [id], foreignKeys: [{ column: "nope", refTable: "x", refColumn: "id" }] }, /isn't a column/],
    [{ name: "t", columns: [id], foreignKeys: [{ column: "id", refTable: "x", refColumn: "id", onDelete: "explode" }] }, /delete rule/],
    [{ name: "a".repeat(64), columns: [id] }, /longer than 63/],
  ];
  for (const [spec, re] of cases) assert.match(buildCreateTable(spec).error, re);
});

test("text default is always a quoted literal, never raw SQL", () => {
  const { sql } = buildCreateTable({
    name: "t",
    columns: [{ name: "a", type: "text", default: { kind: "value", value: "x'); DROP TABLE t; --" } }],
  });
  assert.match(sql, /DEFAULT 'x''\); DROP TABLE t; --'::text/);
});
